{{- if and .Values.backend.enabled .Values.backend.secret.direct.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secret.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "appbaq.backendLabels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ .Values.backend.secret.direct.data.SPRING_DATASOURCE_URL | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.backend.secret.direct.data.SPRING_DATASOURCE_USERNAME | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.backend.secret.direct.data.SPRING_DATASOURCE_PASSWORD | quote }}
  REDIS_HOSTNAME: {{ .Values.backend.secret.direct.data.REDIS_HOSTNAME | quote }}
  REDIS_PASSWORD: {{ .Values.backend.secret.direct.data.REDIS_PASSWORD | quote }}
  BACKEND_API_KEY: {{ .Values.backend.secret.direct.data.BACKEND_API_KEY | quote }}
  STORAGE_ACCOUNT_NAME: {{ .Values.backend.secret.direct.data.STORAGE_ACCOUNT_NAME | quote }}
  STORAGE_SAS_TOKEN: {{ .Values.backend.secret.direct.data.STORAGE_SAS_TOKEN | quote }}
{{- end }}
