global:
  namespace: appbaq-then
  manageNamespace: true
  labels:
    app.kubernetes.io/part-of: appbaq
    environment: non-production
    owner: thomas-enjalbert
frontendLink:
  name: appbaq-frontend
  component: frontend
backend:
  enabled: true
  replicaCount: 1
  image:
    repository: baqacrthomasenjalbertywgh.azurecr.io/appbaq-backend # backend image repository
    tag: 79563c5f # backend image tag
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi
  config:
    constants:
      springProfilesActive: aks
      redisPort: "6380"
      redisSslEnabled: "true"
    infra:
      appCorsAllowedOrigins: # frontend url
      storageContainerName: quiz-results
  secret:
    name: appbaq-backend-secret
    keyVault:
      enabled: false
      usePodIdentity: false
      useVMManagedIdentity: false
      secretProviderClass:
        name: appbaq-backend-kv
        clientId: # aks managed identity client id
        keyVaultName: # key vault name
        tenantId: # tenant id
        syncToK8sSecretName: appbaq-backend-secret
        objects:
          springDatasourceUrl: spring-datasource-url
          springDatasourceUsername: spring-datasource-username
          springDatasourcePassword: spring-datasource-password
          redisHostname: redis-hostname
          redisPassword: redis-password
          backendApiKey: backend-api-key
          storageAccountName: storage-account-name
          storageSasToken: storage-sas-token
networkPolicy:
  enabled: true
  defaultDenyIngress: true
